spring:
  application:
    name: authservice
  datasource:
    hikari:
      connectionTimeout: ${DB_CONN_TIMEOUT}
      maximumPoolSize: ${DB_MAX_POOL}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update