server:
  servlet:
    context-path: /api
spring:
  application:
    name: authservice
  datasource:
    hikari:
      connectionTimeout: ${DB_CONN_TIMEOUT}
      maximumPoolSize: ${DB_MAX_POOL}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

appdata:
  defaults:
    adminPassword: ${ADMIN_PASSWORD}
    adminEmail: ${ADMIN_EMAIL}
    refreshTokenExpiryDays: ${REFRESH_TOKEN_EXP}
    accessTokenExpiryDays: ${ACCESS_TOKEN_EXP}
    jwtSecret: ${JWT_SECRET}


springdoc:
  swagger-ui:
    path: /
