server:
  port: 8080
  servlet:
    context-path: /api
spring:
  webflux:
    problemdetails:
      enabled: true
  application:
    name: gateway
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      max-size: ${DB_MAX_POOL:5}
      initial-size: ${DB_MIN_POOL:2}
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO

appdata:
  defaults:
    jwtSecret: ${JWT_SECRET}
springdoc:
  api-docs:
    path: /api/gateway/api-docs
    enabled: true
  swagger-ui:
    path: /api/gateway/swagger
